/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_msudenver_cs_javaln_syslog_UNIXDomainHandler */

#ifndef _Included_edu_msudenver_cs_javaln_syslog_UNIXDomainHandler
#define _Included_edu_msudenver_cs_javaln_syslog_UNIXDomainHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_msudenver_cs_javaln_syslog_UNIXDomainHandler
 * Method:    sendToUNIXSocket
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_msudenver_cs_javaln_syslog_UNIXDomainHandler_sendToUNIXSocket
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
