#! /bin/bash

dig @127.0.0.1 computingfrontiers.org -p 5000 SOA
dig @127.0.0.1 computingfrontiers.org -p 5000 NS
dig @127.0.0.1 computingfrontiers.org -p 5000 MX
dig @127.0.0.1 computingfrontiers.org -p 5000
dig @127.0.0.1 www.computingfrontiers.org -p 5000
dig @127.0.0.1 mail.computingfrontiers.org -p 5000
dig @127.0.0.1 www.computingfrontiers.org -p 5000 AAAA
dig @127.0.0.1 computingfrontiers.org -p 5000 TXT
dig @127.0.0.1 ftp.computingfrontiers.org -p 5000

exit

insert into records (domain_id, name,type,content,ttl,prio)
    values (1, '27.1.168.192.in-addr.arpa', 'PTR', 'ftp', 86400, 0);
